### ISSUE TITLE
Unclear message suggestions from workshop

### ISSUE THREAD

**Issue by smaria** [udgcirs/marine_ros_conventions_discussion#3]
Several message suggestions/abbreviations from the work shop are not clear (enough) to me:
 - DO
-  ADV  
- Surface time (is this how long the vehicle has been at the surface? suggested tags: comms, mission_
- Environment (this seems too broad, could be tagged mission, but what does it contain?)  
- Hydrophone channel (sure, hydrophone sounds like a great message type, but what does 'channel' imply? information about the SOFAR channel?)

**Comment by ivaughn** [comment]
DO- Dissolved Oxygen
ADV- I'm guessing Acoustic Doppler Velocimeter (e.g., Nortek Vector)
Surface time-- Not sure, I'd guess Expected Time To Surface or a GPS synchronized time message
Environment-- Hopelessly vague, so let's maybe change that to Sound Velocity Profile? (Not to be confused with Sound Velocity Probe)
Hydrophone channel-- the channel number of a hydrophone on a multichannel acquisition board.

**Comment by smaria** [comment]
Thanks, i updated the wiki accordingly.
